### ISSUE TITLE
simplification de requête récursive

### ISSUE THREAD

**Issue by lovasoa** [DSMejantel/Carnet-de-Rucher#1]
J'ai regardé la raquête récursive que vous mentionnez dans les discussions de sqlpage:

https://github.com/DSMejantel/Carnet-de-Rucher/blob/main/ruche.sql#L127-L142

Elle me semble plus compliquée que nécessaire, en particulier parce qu'elle contient des sous-requêtes inutiles.

Je vous propose à la place:

```sql
 WITH RECURSIVE ligne(souche, numero, caractere, début, generation) AS (
  SELECT colonie.souche, colonie.numero, colonie.caractere, colonie.début, 0
  FROM   colonie
  WHERE  colonie.numero = $id
UNION
  SELECT colonie.souche, colonie.numero, colonie.caractere, colonie.début, ligne.generation + 1
  FROM   colonie
  INNER JOIN ligne ON ligne.souche = colonie.numero
)
SELECT 
  numero,
  strftime('%d/%m/%Y',début) as Début, 
  caractere as Caractère
FROM ligne
WHERE generation > 0
ORDER BY generation DESC;
```

https://www.db-fiddle.com/f/9zEhpQMmjuvG1B5Jy6AXhE/0

Par ailleurs, la table colonie me semble un peu étrange: pourquoi a-t-elle à la fois une colonne id et une colonne numero ? Et pourquoi numero est-il du type text ?

Est-ce que l'on ne devrait pas avoir plutôt :

```sql
CREATE TABLE colonie (
    numero INTEGER PRIMARY KEY AUTOINCREMENT,
    ...
);

**Comment by DSMejantel** [comment]
Super,
Merci pour cette relecture. Je viens d'envoyer le fichier réactualisé.
Pour l'ID et le numéro dans la table colonie, c'est une bonne remarque.
En pratique, on pourrait appeler une colonie autrement qu'avec un entier numérique.
Depuis 15 ans certaines caisses ont vu plusieurs colonies s'y succéder au gré des mortalités saisonnières.
De plus, certaines ruches ou ruchettes peuvent contenir deux colonies. Le champ "numéro" avec un type TEXT permettrait d'avoir une colonie 15A et une autre 15B. Ou bien une nouvelle lignée pourrait garder le numéro d'une ruche en y ajoutant une lettre.
J'ai déjà tenté par le passé de suivre les filiations, mais on s'y perd vite après plusieurs saisons sans outil performant.
Pour le moment j'ai des numéros de 1 à 32 pour 29 colonies hivernées.
C'est une question à trancher pour ma gestion du rucher et du logiciel avant le redémarrage du printemps !

**Comment by DSMejantel** [comment]
Correction de Lovasoa validée. En effet, cela est bien plus simple pour obtenir le résultat souhaité. Un grand merci.

**Comment by lovasoa** [comment]
> De plus, certaines ruches ou ruchettes peuvent contenir deux colonies. Le champ "numéro" avec un type TEXT permettrait d'avoir une colonie 15A et une autre 15B. 

Alors le type text est le bon, mais la colonne devrait quand même être la clef primaire et remplacer 'id' :)

```sql
CREATE TABLE colonie (
    numero TEXT PRIMARY KEY,
    ...
);
```

**Comment by DSMejantel** [comment]
Cela sera corrigé lors de la prochaine mise à jour. Au départ la colonne ne portait même pas la contrainte UNIQUE !
Je reste encore un novice en programmation ! Il ne faut pas l'oublier ;-) Mais j'ai un bon mentor !!!
J'ai passé encore peu de temps sur cette application, cela ne fait qu'une dizaine de jours que je construis un élément chaque soir... Cela va tout de même plus vite que pour 'Ecole Inclusive'
