### ISSUE TITLE
Clef primaire de colonie

### ISSUE THREAD

**Issue by DSMejantel** [DSMejantel/Carnet-de-Rucher#2]
> De plus, certaines ruches ou ruchettes peuvent contenir deux colonies. Le champ "numéro" avec un type TEXT permettrait d'avoir une colonie 15A et une autre 15B. 

Alors le type text est le bon, mais la colonne devrait quand même être la clef primaire et remplacer 'id' :)

```sql
CREATE TABLE colonie (
    numero TEXT PRIMARY KEY,
    ...
);
```

_Originally posted by @lovasoa in https://github.com/DSMejantel/Carnet-de-Rucher/issues/1#issuecomment-1913714040_

**Comment by DSMejantel** [comment]
Après avoir travaillé sur la possibilité de changer une colonie d"abeilles de ruche (technique de division fréquente au printemps), je me rappelle pourquoi j'avais deux colonnes qui définissaient la colonie : id et numero.
Pour éviter d'être bloqué par une clé étrangère dans la table 'colvisite' j'avais deux manières de nommer la colonie. J'ai réussi à me débarasser de cette contrainte et je peux ainsi changer de numéro tout en actualisant les tables qui ont besoin de cette donnée mise à jour.
Il me reste à réfléchir à la question de la réutilisation ou non d'une numéro de ruche disparue. Je pense que je vais devoir investir dans des pochoirs pour des numéros à 3 ou 4 chiffres !

**Comment by lovasoa** [comment]
Ah, je pense que je comprends le problème. Est-ce qu'il ne serait pas mieux d'avoir une table ruche en plus de la table colonie ?
Cela permettrait de conserver l'historique et de ne pas s'emmêler les pinceaux lorsqu'une ruche abrite deux colonies ou une colonie change de ruche. Pour ne pas avoir à se compliquer la vie lors des requêtes, vous pourriez faire une vue qui a la même structure que votre table colonie actuelle.

**Comment by DSMejantel** [comment]
Sur le terrain difficile de suivre une colonie avec un numéro différent de celui de la "boîte" qui la contient.
Il ne faut pas que la technique aussi précise et subtile soit-elle deviennent une lourdeur suppléméntaire quand on doit prendre des notes en pleine chaleur, avec des gants et des abeilles (parfois) peu patientes...
Les plaquettes de chiffres ne sont pas si onéreuses que cela et pour les 30 prochaines années je devrai pouvoir rester à des numéros à 3 chiffres !
